const users_DB = [

    {
        id: 1,
        category: 'admin',
        firstName: 'joshua',
        lastName: 'Minani',
        email: 'k.joshua855@gmail.com',
        address: 'Nairobi/kenya',
        bio: 'Youtuber ',
        occupation: 'employee',
        expertise: 'I.T',
        password: 'qwerty',
        confirm_password: 'qwerty',
        account_created : 'on Tue Dec 2012 01:05:00 GMT+0200 (Central Africa Time)',
        account_edited : 'on San Mar 2018 12:23:33 GMT+0200 (Central Africa Time)',
      },
      {
        id: 2,
        category: 'mentor',
        firstName: 'james',
        lastName: 'morinka',
        email: 'test1@gmail.com',
        address: 'Nairobi/kenya',
        bio: 'Youtuber ',
        occupation: 'employee',
        expertise: 'I.T',
        password: 'qwerty',
        confirm_password: 'qwerty',
        account_created : 'on Wed Aug 2009 07:07:07 GMT+0200 (Central Africa Time)',
        account_edited : 'on Mon Dec 2012 09:40:11 GMT+0200 (Central Africa Time)',
      },
      {
      id: 3,
      category: 'mentee',
      firstName: 'milly',
      lastName: 'shirinko',
      email: 'test2@gmail.com',
      address: 'Kigali/Rwanda',
      bio: 'love to care',
      occupation: 'nursing',
      expertise: 'medical',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Sun Oct 2000 20:00:00 GMT+0200 (Central Africa Time)',
    },
    {
      id: 4,
      category: 'mentee',
      firstName: 'Gloria',
      lastName: 'gihozo',
      email: 'test3@gmail.com',
      address: 'Kigali/Rwanda',
      bio: 'love to care',
      occupation: 'nursing',
      expertise: 'medical',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Sat Apri 2005 24:05:00 GMT+0200 (Central Africa Time)',
    },
    {
      id: 5,
      category: 'mentor',
      firstName: 'Ange',
      lastName: 'gihozo',
      email: 'test4@gmail.com',
      address: 'Kigali/Rwanda',
      bio: 'love to care',
      occupation: 'nursing',
      expertise: 'medical',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Fri Jan 2014 15:05:00 GMT+0200 (Central Africa Time)',
      account_edited : 'on Wed May 2013 13:13:13 GMT+0200 (Central Africa Time)',
    },
    {
      id: 6,
      category: 'mentee',
      firstName: 'nelly',
      lastName: 'gihozo',
      email: 'test5@gmail.com',
      address: 'Kigali/Rwanda',
      bio: 'love to care',
      occupation: 'nursing',
      expertise: 'medical',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Mon Jan 2001 01:01:01 GMT+0200 (Central Africa Time)',
    },
    {
      id: 7,
      category: 'mentee',
      firstName: 'Queen',
      lastName: 'kirabo',
      email: 'test5@gmail.com',
      address: 'kampala/uganda',
      bio: 'love to dance',
      occupation: 'clubing',
      expertise: 'party',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Thur Feb 2016 04:05:00 GMT+0200 (Central Africa Time)',
    },
    
    {
      id: 8,
      category: 'admin',
      firstName: 'Eric',
      lastName: 'Ebulu',
      email: 'Ebulu@gmail.com',
      address: 'Lagos/Nigeria',
      bio: 'Agriculture ',
      occupation: 'employee',
      expertise: 'Lands',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Mon Jan 2016 00:00:00 GMT+0200 (Central Africa Time)',
      account_edited : 'on San Mar 2018 12:25:33 GMT+0200 (Central Africa Time)',
    },
    {
      id: 9,
      category: 'mentor',
      firstName: 'ines',
      lastName: 'giramata',
      email: 'test10@gmail.com',
      address: 'Kigali/Rwanda',
      bio: 'love to care',
      occupation: 'nursing',
      expertise: 'medical',
      password: 'qwerty',
      confirm_password: 'qwerty',
      account_created : 'on Fri Jan 2014 15:05:00 GMT+0200 (Central Africa Time)',
      account_edited : 'on Wed May 2013 13:13:13 GMT+0200 (Central Africa Time)',
    }
  ];

  export default users_DB;